version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - 3309:80
    environment:
      - PMA_ARBITRARY=1